[project]
name = "VaGarimpo"
version = "0.1.0"
description = """ web scrapper para raspar vagas freelancer no 99 freela,
    comparar com o curriculo do candidato
    e gerar um rascunho de proposta para enviar ao cliente,
    caso a compatibilidade for maior que 80%"""
authors = [
    {name = "Victor Nogueira", email="victorvalim1@gmail.com"}
]

[tool.ruff]
line-length = 85
extend-exclude = []

[tool.ruff.lint]
preview = true
select = ["I", "E", "F", "W", "PL", "PT"]

[tool.ruff.format]
preview = true
quote-style = "double"

[tool.taskipy.tasks]
# Qualidade de Código
lint = "ruff check ."
format = "ruff format ."
fix = "ruff check --fix && ruff format ."
check = "task fix && task lint"

# Gerenciamento de Dependências
install = "pip install -r requirements.txt"
freeze = "pipreqs . --force"

# Execução e Contêineres (Docker)
run = "docker compose up --build"
scraper = "MODE=scraper docker compose up --build"
jobs = "MODE=get-job docker compose up --build"